services:
  server:
    build:
      context: .
    container_name: Server
    ports:
      - 3001:3001
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - ./server:/usr/src/app/server
    command: npm run server
  app:
    build:
      context: .
    container_name: Client
    volumes:
      - ./:/usr/src/app
      - ./client:/usr/src/app/client
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    command: npm run client
