name: restaurant-ordering-system CI Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: cd /client
    - run: npm test 
